default:
  adx_period: 14
  adx_threshold: 25
  ce_gap: 40
  ce_quantity: 65
  ce_reset_gap: 30
  ce_start_point: 0
  ce_symbol_gap: 800
  ema_period: 20
  entry_filter_type: NONE
  exchange: NFO
  history_period_days: 5
  index_symbol: NSE:NIFTY 50
  min_price_to_sell: 15.0
  order_type: MARKET
  pe_gap: 40
  pe_quantity: 65
  pe_reset_gap: 30
  pe_start_point: 0
  pe_symbol_gap: 800
  product_type: NRML
  rsi_max: 50
  rsi_min: 50
  rsi_period: 14
  sell_multiplier_threshold: 3
  symbol_initials: NIFTY26FEB
  tag: Survivor
  trans_type: SELL
